name: tactics_fc_utilities
description: Shared utilities and models for the Soccer Manager project
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  test: ^1.25.8
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
